title: Cole's Closet
author: Mace
email: macejicm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a cool place to learn about fun stuff. Send and email if you like the material. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
